### ISSUE TITLE
Can't Click to TP

### ISSUE THREAD

**Issue by Y0ungSandwich** [itsmeow/ClaimIt#4]
**Describe the bug**
While using the command /claimit claim list You can not teleport. Instead you get an Exception in chat. There is no further info produced in the console. 

**To Reproduce**
Type /claimit claim list
Click Coordinates 

**Expected behavior**
Clicking the Location Coordinates provided should TP the user to that location.

**Screenshots**
https://imgur.com/a/wAXhg5V

**Versions**
 - Forge Version: 14.23.5.2847
 - SpongeForge Version (if applicable): spongeforge-1.12.2-2838-7.1.9
 - Mod Version: ClaimIt v1.2.0
 - API Version: ClaimIt API v1.2.0

**Comment by itsmeow** [comment]
Ah, I believe this is caused by that command executing another command in the shorthand form "/ci", which many other "Essentials"-like mods have used for "/clear" or "/clearinventory"

Basically the teleport executes another claimit command "/claimit admin tpdimxz" but I must've typed "/ci admin tpdimxz" in the code which is causing it to fail because another command exists on /ci. Perhaps you can configure the plugin or mod that adds /ci to have a different alias?

**Comment by Y0ungSandwich** [comment]
I believe its gonna be in Nucleus. I dont think I can change the alias but Ill poke around. I wonder if I set the clear inventory permission to false if it will let this work.

**Comment by Y0ungSandwich** [comment]
Nevermind apparently I can edit the alias in Nucleus. Ill disable and give it a shot. Thanks.

**Comment by itsmeow** [comment]
Check this out yeah https://nucleuspowered.org/docs/faqs.html#use-minecraft-command

**Comment by Y0ungSandwich** [comment]
Thanks for the help! We are digging this mod. Only things we would love to see are an inspection item and an admin claim mode. Keep up the good work!
